package main

import "core:fmt"
import "core:os"

init_shader_and_watchers :: proc (watchers: ^[dynamic] Watcher, common_watcher: Watcher_Id, input: string, bytes_allocator: Allocator, output_extension := ".spv") -> Shader {
    result, ok := compile_and_load_shader(input, bytes_allocator)
    if !ok {
        assert(false, fmt.tprintf("Failed to initially load the shader `%v`", input))
    }
    result.source_watcher = watchers_make(watchers, result.input)
    result.common_watcher = common_watcher
    return result
}

compile_and_load_shader :: proc (input: string, bytes_allocator: Allocator, output_extension := ".spv", old: ^Shader = nil) -> (Shader, bool) {
    cmd: Cmd
    cmd.allocator = context.temp_allocator
    
    shader_output := fmt.tprintf("%v%v", input, output_extension)
    
    append(&cmd, "C:/tools/VulkanSDK/1.4.350.0/Bin/glslc.exe")
    append(&cmd, "--target-env=vulkan1.4")
    append(&cmd, "-o", shader_output)
    if ODIN_DEBUG {
        append(&cmd, "-g") // embed shader source code for renderdoc
    }
    if Optimized {
        append(&cmd, "-O")
    }
    append(&cmd, input)
    
    result: Shader
    if old != nil {
        result = old^
    }
    result.input = input
    
    stdout: string
    stderr: string
    if !run_command(&cmd, or_exit = false, stdout = &stdout, stderr = &stderr) {
        fmt.eprintfln("Failed to run command to compile shader '%v'")
        return result, false
    }
    
    if stdout != "" {
        fmt.printfln("Hotreload output: %v", stdout)
    }
    
    if stderr != "" {
        fmt.printfln("Hotreload error: %v", stderr)
        return result, false
    }
    
    shader_bytes, err := os.read_entire_file(shader_output, bytes_allocator)
    if err != nil {
        fmt.printfln("Could not load the output file of '%v', which is '%v': %v", result.input, shader_output, os.error_string(err))
        return result, false
    }
    
    if old != nil {
        delete(old.bytes)
    }
    
    result.bytes = shader_bytes
    
    {
        shader_code := slice_from_parts(u32, raw_data(shader_bytes), len(shader_bytes) / 4)
        
        assert(shader_code[0] == SpvMagicNumber)
        id_bound := shader_code[3]
        
        Id :: struct {
            opcode:   SpvOp,
            type_id:  u32,
            
            set: u32,
            binding: u32,
            
            constant: u32,
            storage_class: SpvStorageClass,
        }
        ids := make([] Id, id_bound, context.temp_allocator)
        
        code     := shader_code[5:]
        
        local_size: [3] i32 = -1
        
        for len(code) != 0 {
            opcode     := cast(SpvOp) cast(u16) ((code[0] >>  0) & 0xFFFF)
            word_count := cast(u16) ((code[0] >> 16) & 0xFFFF)
            
            #partial switch opcode {
            case .EntryPoint:
                execution_model := cast(SpvExecutionModel) code[1]
                
                #partial switch execution_model {
                case .Vertex:     result.stage = .VERTEX
                case .Fragment:   result.stage = .FRAGMENT
                case .MeshEXT:    result.stage = .MESH_EXT
                case .TaskEXT:    result.stage = .TASK_EXT
                case .GLCompute:  result.stage = .COMPUTE
                }
            
            case .ExecutionMode:
                mode := cast(SpvExecutionMode) code[2]
                #partial switch mode {
                case .LocalSize:
                    result.local_size.x = code[3]
                    result.local_size.y = code[4]
                    result.local_size.z = code[5]
                }
                
            case .ExecutionModeId:
                mode := cast(SpvExecutionMode) code[2]
                #partial switch mode {
                case .LocalSizeId:
                    local_size.x = cast(i32) code[3]
                    local_size.y = cast(i32) code[4]
                    local_size.z = cast(i32) code[5]
                }
                
            case .Constant:
                id := code[2]
                assert(ids[id].opcode == {})
                
                ids[id] = { 
                    opcode   = opcode,
                    type_id  = code[1],
                    constant = code[3], 
                }
                    
            case .Variable:
                id := code[2]
                assert(ids[id].opcode == {})
                
                ids[id] = { 
                    opcode        = opcode,
                    type_id       = code[1],
                    storage_class = cast(SpvStorageClass) code[3], 
                }
                
            case .TypePointer:
                id := code[1]
                assert(ids[id].opcode == {})
                
                ids[id] = { 
                    opcode        = opcode,
                    type_id       = code[3],
                    storage_class = cast(SpvStorageClass) code[2], 
                }
            }
            
            code = code[word_count:]
        }
        
        for id in ids {
            if id.opcode == .Variable && (id.storage_class == .Uniform || id.storage_class == .UniformConstant || id.storage_class == .StorageBuffer ) {
                assert(id.set == 0)
                assert(id.binding < 32)
                assert(ids[id.type_id].opcode == .TypePointer)
                
                assert(id.binding not_in result.resource_mask)
                
                type_kind := ids[ids[id.type_id].type_id].opcode
                
                #partial switch type_kind {
                case .TypeStruct:       
                    result.resource_types[id.binding] = .STORAGE_BUFFER
                    result.resource_mask += { id.binding }
                    
                case .TypeImage:        
                    result.resource_types[id.binding] = .STORAGE_IMAGE
                    result.resource_mask += { id.binding }
                    
                case .TypeSampler:      
                    result.resource_types[id.binding] = .SAMPLER
                    result.resource_mask += { id.binding }
                    
                case .TypeSampledImage: 
                    result.resource_types[id.binding] = .COMBINED_IMAGE_SAMPLER
                    result.resource_mask += { id.binding }
                    
                }
            }
            
            if id.opcode == .Variable && id.storage_class == .PushConstant {
                result.use_push_constants = true
            }
        }
        
        if result.stage == .COMPUTE {
            for it in 0..<3 {
                if local_size[it] >= 0 {
                    assert(ids[local_size[it]].opcode == .Constant)
                    result.local_size[it] = ids[local_size[it]].constant
                }
            }
            
            assert(result.local_size != 0)
        }
    }
    
    return result, true
}

get_group_count :: proc (shader: Shader, total_count: u32) -> u32 {
    result := (total_count + shader.local_size.x-1) / shader.local_size.x
    return result
}

////////////////////////////////////////////////
// copy-pasted from https://github.com/KhronosGroup/SPIRV-Headers/blob/main/include/spirv/unified1/spirv.h

@(private="file")
SpvMagicNumber :: 0x07230203

@(private="file")
SpvExecutionMode :: enum  u32 {
    Invocations = 0,
    SpacingEqual = 1,
    SpacingFractionalEven = 2,
    SpacingFractionalOdd = 3,
    VertexOrderCw = 4,
    VertexOrderCcw = 5,
    PixelCenterInteger = 6,
    OriginUpperLeft = 7,
    OriginLowerLeft = 8,
    EarlyFragmentTests = 9,
    PointMode = 10,
    Xfb = 11,
    DepthReplacing = 12,
    DepthGreater = 14,
    DepthLess = 15,
    DepthUnchanged = 16,
    LocalSize = 17,
    LocalSizeHint = 18,
    InputPoints = 19,
    InputLines = 20,
    InputLinesAdjacency = 21,
    Triangles = 22,
    InputTrianglesAdjacency = 23,
    Quads = 24,
    Isolines = 25,
    OutputVertices = 26,
    OutputPoints = 27,
    OutputLineStrip = 28,
    OutputTriangleStrip = 29,
    VecTypeHint = 30,
    ContractionOff = 31,
    Initializer = 33,
    Finalizer = 34,
    SubgroupSize = 35,
    SubgroupsPerWorkgroup = 36,
    SubgroupsPerWorkgroupId = 37,
    LocalSizeId = 38,
    LocalSizeHintId = 39,
    NonCoherentColorAttachmentReadEXT = 4169,
    NonCoherentDepthAttachmentReadEXT = 4170,
    NonCoherentStencilAttachmentReadEXT = 4171,
    SubgroupUniformControlFlowKHR = 4421,
    PostDepthCoverage = 4446,
    DenormPreserve = 4459,
    DenormFlushToZero = 4460,
    SignedZeroInfNanPreserve = 4461,
    RoundingModeRTE = 4462,
    RoundingModeRTZ = 4463,
    NonCoherentTileAttachmentReadQCOM = 4489,
    TileShadingRateQCOM = 4490,
    EarlyAndLateFragmentTestsAMD = 5017,
    StencilRefReplacingEXT = 5027,
    CoalescingAMDX = 5069,
    IsApiEntryAMDX = 5070,
    MaxNodeRecursionAMDX = 5071,
    StaticNumWorkgroupsAMDX = 5072,
    ShaderIndexAMDX = 5073,
    MaxNumWorkgroupsAMDX = 5077,
    StencilRefUnchangedFrontAMD = 5079,
    StencilRefGreaterFrontAMD = 5080,
    StencilRefLessFrontAMD = 5081,
    StencilRefUnchangedBackAMD = 5082,
    StencilRefGreaterBackAMD = 5083,
    StencilRefLessBackAMD = 5084,
    QuadDerivativesKHR = 5088,
    RequireFullQuadsKHR = 5089,
    SharesInputWithAMDX = 5102,
    ArithmeticPoisonKHR = 5157,
    OutputLinesEXT = 5269,
    OutputLinesNV = 5269,
    OutputPrimitivesEXT = 5270,
    OutputPrimitivesNV = 5270,
    DerivativeGroupQuadsKHR = 5289,
    DerivativeGroupQuadsNV = 5289,
    DerivativeGroupLinearKHR = 5290,
    DerivativeGroupLinearNV = 5290,
    OutputTrianglesEXT = 5298,
    OutputTrianglesNV = 5298,
    PixelInterlockOrderedEXT = 5366,
    PixelInterlockUnorderedEXT = 5367,
    SampleInterlockOrderedEXT = 5368,
    SampleInterlockUnorderedEXT = 5369,
    ShadingRateInterlockOrderedEXT = 5370,
    ShadingRateInterlockUnorderedEXT = 5371,
    Shader64BitIndexingEXT = 5427,
    SharedLocalMemorySizeINTEL = 5618,
    RoundingModeRTPINTEL = 5620,
    RoundingModeRTNINTEL = 5621,
    FloatingPointModeALTINTEL = 5622,
    FloatingPointModeIEEEINTEL = 5623,
    MaxWorkgroupSizeINTEL = 5893,
    MaxWorkDimINTEL = 5894,
    NoGlobalOffsetINTEL = 5895,
    NumSIMDWorkitemsINTEL = 5896,
    SchedulerTargetFmaxMhzINTEL = 5903,
    MaximallyReconvergesKHR = 6023,
    FPFastMathDefault = 6028,
    OpacityMicromapIdKHR = 6031,
    StreamingInterfaceINTEL = 6154,
    RegisterMapInterfaceINTEL = 6160,
    NamedBarrierCountINTEL = 6417,
    MaximumRegistersINTEL = 6461,
    MaximumRegistersIdINTEL = 6462,
    NamedMaximumRegistersINTEL = 6463,
    Max = 0x7fffffff,
}

@(private="file")
SpvExecutionModel :: enum u32 { 
    Vertex = 0,
    TessellationControl = 1,
    TessellationEvaluation = 2,
    Geometry = 3,
    Fragment = 4,
    GLCompute = 5,
    Kernel = 6,
    TaskNV = 5267,
    MeshNV = 5268,
    RayGenerationKHR = 5313,
    RayGenerationNV = 5313,
    IntersectionKHR = 5314,
    IntersectionNV = 5314,
    AnyHitKHR = 5315,
    AnyHitNV = 5315,
    ClosestHitKHR = 5316,
    ClosestHitNV = 5316,
    MissKHR = 5317,
    MissNV = 5317,
    CallableKHR = 5318,
    CallableNV = 5318,
    TaskEXT = 5364,
    MeshEXT = 5365,
    Max = 0x7fffffff,
}

@(private="file")
SpvStorageClass :: enum u32 {
    UniformConstant = 0,
    Input = 1,
    Uniform = 2,
    Output = 3,
    Workgroup = 4,
    CrossWorkgroup = 5,
    Private = 6,
    Function = 7,
    Generic = 8,
    PushConstant = 9,
    AtomicCounter = 10,
    Image = 11,
    StorageBuffer = 12,
    TileImageEXT = 4172,
    TileAttachmentQCOM = 4491,
    NodePayloadAMDX = 5068,
    CallableDataKHR = 5328,
    CallableDataNV = 5328,
    IncomingCallableDataKHR = 5329,
    IncomingCallableDataNV = 5329,
    RayPayloadKHR = 5338,
    RayPayloadNV = 5338,
    HitAttributeKHR = 5339,
    HitAttributeNV = 5339,
    IncomingRayPayloadKHR = 5342,
    IncomingRayPayloadNV = 5342,
    ShaderRecordBufferKHR = 5343,
    ShaderRecordBufferNV = 5343,
    PhysicalStorageBuffer = 5349,
    PhysicalStorageBufferEXT = 5349,
    HitObjectAttributeNV = 5385,
    TaskPayloadWorkgroupEXT = 5402,
    HitObjectAttributeEXT = 5411,
    CodeSectionINTEL = 5605,
    DeviceOnlyALTERA = 5936,
    DeviceOnlyINTEL = 5936,
    HostOnlyALTERA = 5937,
    HostOnlyINTEL = 5937,
    Max = 0x7fffffff,
}

@(private="file")
SpvOp:: enum u32 {
    Nop = 0,
    Undef = 1,
    SourceContinued = 2,
    Source = 3,
    SourceExtension = 4,
    Name = 5,
    MemberName = 6,
    String = 7,
    Line = 8,
    Extension = 10,
    ExtInstImport = 11,
    ExtInst = 12,
    MemoryModel = 14,
    EntryPoint = 15,
    ExecutionMode = 16,
    Capability = 17,
    TypeVoid = 19,
    TypeBool = 20,
    TypeInt = 21,
    TypeFloat = 22,
    TypeVector = 23,
    TypeMatrix = 24,
    TypeImage = 25,
    TypeSampler = 26,
    TypeSampledImage = 27,
    TypeArray = 28,
    TypeRuntimeArray = 29,
    TypeStruct = 30,
    TypeOpaque = 31,
    TypePointer = 32,
    TypeFunction = 33,
    TypeEvent = 34,
    TypeDeviceEvent = 35,
    TypeReserveId = 36,
    TypeQueue = 37,
    TypePipe = 38,
    TypeForwardPointer = 39,
    ConstantTrue = 41,
    ConstantFalse = 42,
    Constant = 43,
    ConstantComposite = 44,
    ConstantSampler = 45,
    ConstantNull = 46,
    SpecConstantTrue = 48,
    SpecConstantFalse = 49,
    SpecConstant = 50,
    SpecConstantComposite = 51,
    SpecConstantOp = 52,
    Function = 54,
    FunctionParameter = 55,
    FunctionEnd = 56,
    FunctionCall = 57,
    Variable = 59,
    ImageTexelPointer = 60,
    Load = 61,
    Store = 62,
    CopyMemory = 63,
    CopyMemorySized = 64,
    AccessChain = 65,
    InBoundsAccessChain = 66,
    PtrAccessChain = 67,
    ArrayLength = 68,
    GenericPtrMemSemantics = 69,
    InBoundsPtrAccessChain = 70,
    Decorate = 71,
    MemberDecorate = 72,
    DecorationGroup = 73,
    GroupDecorate = 74,
    GroupMemberDecorate = 75,
    VectorExtractDynamic = 77,
    VectorInsertDynamic = 78,
    VectorShuffle = 79,
    CompositeConstruct = 80,
    CompositeExtract = 81,
    CompositeInsert = 82,
    CopyObject = 83,
    Transpose = 84,
    SampledImage = 86,
    ImageSampleImplicitLod = 87,
    ImageSampleExplicitLod = 88,
    ImageSampleDrefImplicitLod = 89,
    ImageSampleDrefExplicitLod = 90,
    ImageSampleProjImplicitLod = 91,
    ImageSampleProjExplicitLod = 92,
    ImageSampleProjDrefImplicitLod = 93,
    ImageSampleProjDrefExplicitLod = 94,
    ImageFetch = 95,
    ImageGather = 96,
    ImageDrefGather = 97,
    ImageRead = 98,
    ImageWrite = 99,
    Image = 100,
    ImageQueryFormat = 101,
    ImageQueryOrder = 102,
    ImageQuerySizeLod = 103,
    ImageQuerySize = 104,
    ImageQueryLod = 105,
    ImageQueryLevels = 106,
    ImageQuerySamples = 107,
    ConvertFToU = 109,
    ConvertFToS = 110,
    ConvertSToF = 111,
    ConvertUToF = 112,
    UConvert = 113,
    SConvert = 114,
    FConvert = 115,
    QuantizeToF16 = 116,
    ConvertPtrToU = 117,
    SatConvertSToU = 118,
    SatConvertUToS = 119,
    ConvertUToPtr = 120,
    PtrCastToGeneric = 121,
    GenericCastToPtr = 122,
    GenericCastToPtrExplicit = 123,
    Bitcast = 124,
    SNegate = 126,
    FNegate = 127,
    IAdd = 128,
    FAdd = 129,
    ISub = 130,
    FSub = 131,
    IMul = 132,
    FMul = 133,
    UDiv = 134,
    SDiv = 135,
    FDiv = 136,
    UMod = 137,
    SRem = 138,
    SMod = 139,
    FRem = 140,
    FMod = 141,
    VectorTimesScalar = 142,
    MatrixTimesScalar = 143,
    VectorTimesMatrix = 144,
    MatrixTimesVector = 145,
    MatrixTimesMatrix = 146,
    OuterProduct = 147,
    Dot = 148,
    IAddCarry = 149,
    ISubBorrow = 150,
    UMulExtended = 151,
    SMulExtended = 152,
    Any = 154,
    All = 155,
    IsNan = 156,
    IsInf = 157,
    IsFinite = 158,
    IsNormal = 159,
    SignBitSet = 160,
    LessOrGreater = 161,
    Ordered = 162,
    Unordered = 163,
    LogicalEqual = 164,
    LogicalNotEqual = 165,
    LogicalOr = 166,
    LogicalAnd = 167,
    LogicalNot = 168,
    Select = 169,
    IEqual = 170,
    INotEqual = 171,
    UGreaterThan = 172,
    SGreaterThan = 173,
    UGreaterThanEqual = 174,
    SGreaterThanEqual = 175,
    ULessThan = 176,
    SLessThan = 177,
    ULessThanEqual = 178,
    SLessThanEqual = 179,
    FOrdEqual = 180,
    FUnordEqual = 181,
    FOrdNotEqual = 182,
    FUnordNotEqual = 183,
    FOrdLessThan = 184,
    FUnordLessThan = 185,
    FOrdGreaterThan = 186,
    FUnordGreaterThan = 187,
    FOrdLessThanEqual = 188,
    FUnordLessThanEqual = 189,
    FOrdGreaterThanEqual = 190,
    FUnordGreaterThanEqual = 191,
    ShiftRightLogical = 194,
    ShiftRightArithmetic = 195,
    ShiftLeftLogical = 196,
    BitwiseOr = 197,
    BitwiseXor = 198,
    BitwiseAnd = 199,
    Not = 200,
    BitFieldInsert = 201,
    BitFieldSExtract = 202,
    BitFieldUExtract = 203,
    BitReverse = 204,
    BitCount = 205,
    DPdx = 207,
    DPdy = 208,
    Fwidth = 209,
    DPdxFine = 210,
    DPdyFine = 211,
    FwidthFine = 212,
    DPdxCoarse = 213,
    DPdyCoarse = 214,
    FwidthCoarse = 215,
    EmitVertex = 218,
    EndPrimitive = 219,
    EmitStreamVertex = 220,
    EndStreamPrimitive = 221,
    ControlBarrier = 224,
    MemoryBarrier = 225,
    AtomicLoad = 227,
    AtomicStore = 228,
    AtomicExchange = 229,
    AtomicCompareExchange = 230,
    AtomicCompareExchangeWeak = 231,
    AtomicIIncrement = 232,
    AtomicIDecrement = 233,
    AtomicIAdd = 234,
    AtomicISub = 235,
    AtomicSMin = 236,
    AtomicUMin = 237,
    AtomicSMax = 238,
    AtomicUMax = 239,
    AtomicAnd = 240,
    AtomicOr = 241,
    AtomicXor = 242,
    Phi = 245,
    LoopMerge = 246,
    SelectionMerge = 247,
    Label = 248,
    Branch = 249,
    BranchConditional = 250,
    Switch = 251,
    Kill = 252,
    Return = 253,
    ReturnValue = 254,
    Unreachable = 255,
    LifetimeStart = 256,
    LifetimeStop = 257,
    GroupAsyncCopy = 259,
    GroupWaitEvents = 260,
    GroupAll = 261,
    GroupAny = 262,
    GroupBroadcast = 263,
    GroupIAdd = 264,
    GroupFAdd = 265,
    GroupFMin = 266,
    GroupUMin = 267,
    GroupSMin = 268,
    GroupFMax = 269,
    GroupUMax = 270,
    GroupSMax = 271,
    ReadPipe = 274,
    WritePipe = 275,
    ReservedReadPipe = 276,
    ReservedWritePipe = 277,
    ReserveReadPipePackets = 278,
    ReserveWritePipePackets = 279,
    CommitReadPipe = 280,
    CommitWritePipe = 281,
    IsValidReserveId = 282,
    GetNumPipePackets = 283,
    GetMaxPipePackets = 284,
    GroupReserveReadPipePackets = 285,
    GroupReserveWritePipePackets = 286,
    GroupCommitReadPipe = 287,
    GroupCommitWritePipe = 288,
    EnqueueMarker = 291,
    EnqueueKernel = 292,
    GetKernelNDrangeSubGroupCount = 293,
    GetKernelNDrangeMaxSubGroupSize = 294,
    GetKernelWorkGroupSize = 295,
    GetKernelPreferredWorkGroupSizeMultiple = 296,
    RetainEvent = 297,
    ReleaseEvent = 298,
    CreateUserEvent = 299,
    IsValidEvent = 300,
    SetUserEventStatus = 301,
    CaptureEventProfilingInfo = 302,
    GetDefaultQueue = 303,
    BuildNDRange = 304,
    ImageSparseSampleImplicitLod = 305,
    ImageSparseSampleExplicitLod = 306,
    ImageSparseSampleDrefImplicitLod = 307,
    ImageSparseSampleDrefExplicitLod = 308,
    ImageSparseSampleProjImplicitLod = 309,
    ImageSparseSampleProjExplicitLod = 310,
    ImageSparseSampleProjDrefImplicitLod = 311,
    ImageSparseSampleProjDrefExplicitLod = 312,
    ImageSparseFetch = 313,
    ImageSparseGather = 314,
    ImageSparseDrefGather = 315,
    ImageSparseTexelsResident = 316,
    NoLine = 317,
    AtomicFlagTestAndSet = 318,
    AtomicFlagClear = 319,
    ImageSparseRead = 320,
    SizeOf = 321,
    TypePipeStorage = 322,
    ConstantPipeStorage = 323,
    CreatePipeFromPipeStorage = 324,
    GetKernelLocalSizeForSubgroupCount = 325,
    GetKernelMaxNumSubgroups = 326,
    TypeNamedBarrier = 327,
    NamedBarrierInitialize = 328,
    MemoryNamedBarrier = 329,
    ModuleProcessed = 330,
    ExecutionModeId = 331,
    DecorateId = 332,
    GroupNonUniformElect = 333,
    GroupNonUniformAll = 334,
    GroupNonUniformAny = 335,
    GroupNonUniformAllEqual = 336,
    GroupNonUniformBroadcast = 337,
    GroupNonUniformBroadcastFirst = 338,
    GroupNonUniformBallot = 339,
    GroupNonUniformInverseBallot = 340,
    GroupNonUniformBallotBitExtract = 341,
    GroupNonUniformBallotBitCount = 342,
    GroupNonUniformBallotFindLSB = 343,
    GroupNonUniformBallotFindMSB = 344,
    GroupNonUniformShuffle = 345,
    GroupNonUniformShuffleXor = 346,
    GroupNonUniformShuffleUp = 347,
    GroupNonUniformShuffleDown = 348,
    GroupNonUniformIAdd = 349,
    GroupNonUniformFAdd = 350,
    GroupNonUniformIMul = 351,
    GroupNonUniformFMul = 352,
    GroupNonUniformSMin = 353,
    GroupNonUniformUMin = 354,
    GroupNonUniformFMin = 355,
    GroupNonUniformSMax = 356,
    GroupNonUniformUMax = 357,
    GroupNonUniformFMax = 358,
    GroupNonUniformBitwiseAnd = 359,
    GroupNonUniformBitwiseOr = 360,
    GroupNonUniformBitwiseXor = 361,
    GroupNonUniformLogicalAnd = 362,
    GroupNonUniformLogicalOr = 363,
    GroupNonUniformLogicalXor = 364,
    GroupNonUniformQuadBroadcast = 365,
    GroupNonUniformQuadSwap = 366,
    CopyLogical = 400,
    PtrEqual = 401,
    PtrNotEqual = 402,
    PtrDiff = 403,
    ColorAttachmentReadEXT = 4160,
    DepthAttachmentReadEXT = 4161,
    StencilAttachmentReadEXT = 4162,
    TypeTensorARM = 4163,
    TensorReadARM = 4164,
    TensorWriteARM = 4165,
    TensorQuerySizeARM = 4166,
    GraphConstantARM = 4181,
    GraphEntryPointARM = 4182,
    GraphARM = 4183,
    GraphInputARM = 4184,
    GraphSetOutputARM = 4185,
    GraphEndARM = 4186,
    TypeGraphARM = 4190,
    TerminateInvocation = 4416,
    TypeUntypedPointerKHR = 4417,
    UntypedVariableKHR = 4418,
    UntypedAccessChainKHR = 4419,
    UntypedInBoundsAccessChainKHR = 4420,
    SubgroupBallotKHR = 4421,
    SubgroupFirstInvocationKHR = 4422,
    UntypedPtrAccessChainKHR = 4423,
    UntypedInBoundsPtrAccessChainKHR = 4424,
    UntypedArrayLengthKHR = 4425,
    UntypedPrefetchKHR = 4426,
    FmaKHR = 4427,
    SubgroupAllKHR = 4428,
    SubgroupAnyKHR = 4429,
    SubgroupAllEqualKHR = 4430,
    GroupNonUniformRotateKHR = 4431,
    SubgroupReadInvocationKHR = 4432,
    ExtInstWithForwardRefsKHR = 4433,
    UntypedGroupAsyncCopyKHR = 4434,
    TraceRayKHR = 4445,
    ExecuteCallableKHR = 4446,
    ConvertUToAccelerationStructureKHR = 4447,
    IgnoreIntersectionKHR = 4448,
    TerminateRayKHR = 4449,
    SDot = 4450,
    SDotKHR = 4450,
    UDot = 4451,
    UDotKHR = 4451,
    SUDot = 4452,
    SUDotKHR = 4452,
    SDotAccSat = 4453,
    SDotAccSatKHR = 4453,
    UDotAccSat = 4454,
    UDotAccSatKHR = 4454,
    SUDotAccSat = 4455,
    SUDotAccSatKHR = 4455,
    TypeCooperativeMatrixKHR = 4456,
    CooperativeMatrixLoadKHR = 4457,
    CooperativeMatrixStoreKHR = 4458,
    CooperativeMatrixMulAddKHR = 4459,
    CooperativeMatrixLengthKHR = 4460,
    ConstantCompositeReplicateEXT = 4461,
    SpecConstantCompositeReplicateEXT = 4462,
    CompositeConstructReplicateEXT = 4463,
    TypeRayQueryKHR = 4472,
    RayQueryInitializeKHR = 4473,
    RayQueryTerminateKHR = 4474,
    RayQueryGenerateIntersectionKHR = 4475,
    RayQueryConfirmIntersectionKHR = 4476,
    RayQueryProceedKHR = 4477,
    RayQueryGetIntersectionTypeKHR = 4479,
    ImageSampleWeightedQCOM = 4480,
    ImageBoxFilterQCOM = 4481,
    ImageBlockMatchSSDQCOM = 4482,
    ImageBlockMatchSADQCOM = 4483,
    BitCastArrayQCOM = 4497,
    ImageBlockMatchWindowSSDQCOM = 4500,
    ImageBlockMatchWindowSADQCOM = 4501,
    ImageBlockMatchGatherSSDQCOM = 4502,
    ImageBlockMatchGatherSADQCOM = 4503,
    CompositeConstructCoopMatQCOM = 4540,
    CompositeExtractCoopMatQCOM = 4541,
    ExtractSubArrayQCOM = 4542,
    GroupIAddNonUniformAMD = 5000,
    GroupFAddNonUniformAMD = 5001,
    GroupFMinNonUniformAMD = 5002,
    GroupUMinNonUniformAMD = 5003,
    GroupSMinNonUniformAMD = 5004,
    GroupFMaxNonUniformAMD = 5005,
    GroupUMaxNonUniformAMD = 5006,
    GroupSMaxNonUniformAMD = 5007,
    FragmentMaskFetchAMD = 5011,
    FragmentFetchAMD = 5012,
    ReadClockKHR = 5056,
    AllocateNodePayloadsAMDX = 5074,
    EnqueueNodePayloadsAMDX = 5075,
    TypeNodePayloadArrayAMDX = 5076,
    FinishWritingNodePayloadAMDX = 5078,
    NodePayloadArrayLengthAMDX = 5090,
    IsNodePayloadValidAMDX = 5101,
    ConstantStringAMDX = 5103,
    SpecConstantStringAMDX = 5104,
    GroupNonUniformQuadAllKHR = 5110,
    GroupNonUniformQuadAnyKHR = 5111,
    TypeBufferEXT = 5115,
    BufferPointerEXT = 5119,
    AbortKHR = 5121,
    UntypedImageTexelPointerEXT = 5126,
    MemberDecorateIdEXT = 5127,
    ConstantSizeOfEXT = 5129,
    ConstantDataKHR = 5147,
    SpecConstantDataKHR = 5148,
    PoisonKHR = 5158,
    FreezeKHR = 5159,
    HitObjectRecordHitMotionNV = 5249,
    HitObjectRecordHitWithIndexMotionNV = 5250,
    HitObjectRecordMissMotionNV = 5251,
    HitObjectGetWorldToObjectNV = 5252,
    HitObjectGetObjectToWorldNV = 5253,
    HitObjectGetObjectRayDirectionNV = 5254,
    HitObjectGetObjectRayOriginNV = 5255,
    HitObjectTraceRayMotionNV = 5256,
    HitObjectGetShaderRecordBufferHandleNV = 5257,
    HitObjectGetShaderBindingTableRecordIndexNV = 5258,
    HitObjectRecordEmptyNV = 5259,
    HitObjectTraceRayNV = 5260,
    HitObjectRecordHitNV = 5261,
    HitObjectRecordHitWithIndexNV = 5262,
    HitObjectRecordMissNV = 5263,
    HitObjectExecuteShaderNV = 5264,
    HitObjectGetCurrentTimeNV = 5265,
    HitObjectGetAttributesNV = 5266,
    HitObjectGetHitKindNV = 5267,
    HitObjectGetPrimitiveIndexNV = 5268,
    HitObjectGetGeometryIndexNV = 5269,
    HitObjectGetInstanceIdNV = 5270,
    HitObjectGetInstanceCustomIndexNV = 5271,
    HitObjectGetWorldRayDirectionNV = 5272,
    HitObjectGetWorldRayOriginNV = 5273,
    HitObjectGetRayTMaxNV = 5274,
    HitObjectGetRayTMinNV = 5275,
    HitObjectIsEmptyNV = 5276,
    HitObjectIsHitNV = 5277,
    HitObjectIsMissNV = 5278,
    ReorderThreadWithHitObjectNV = 5279,
    ReorderThreadWithHintNV = 5280,
    TypeHitObjectNV = 5281,
    ImageSampleFootprintNV = 5283,
    TypeCooperativeVectorNV = 5288,
    TypeVectorIdEXT = 5288,
    CooperativeVectorMatrixMulNV = 5289,
    CooperativeVectorOuterProductAccumulateNV = 5290,
    CooperativeVectorReduceSumAccumulateNV = 5291,
    CooperativeVectorMatrixMulAddNV = 5292,
    CooperativeMatrixConvertNV = 5293,
    EmitMeshTasksEXT = 5294,
    SetMeshOutputsEXT = 5295,
    GroupNonUniformPartitionEXT = 5296,
    GroupNonUniformPartitionNV = 5296,
    WritePackedPrimitiveIndices4x8NV = 5299,
    FetchMicroTriangleVertexPositionNV = 5300,
    FetchMicroTriangleVertexBarycentricNV = 5301,
    CooperativeVectorLoadNV = 5302,
    CooperativeVectorStoreNV = 5303,
    HitObjectRecordFromQueryEXT = 5304,
    HitObjectRecordMissEXT = 5305,
    HitObjectRecordMissMotionEXT = 5306,
    HitObjectGetIntersectionTriangleVertexPositionsEXT = 5307,
    HitObjectGetRayFlagsEXT = 5308,
    HitObjectSetShaderBindingTableRecordIndexEXT = 5309,
    HitObjectReorderExecuteShaderEXT = 5310,
    HitObjectTraceReorderExecuteEXT = 5311,
    HitObjectTraceMotionReorderExecuteEXT = 5312,
    TypeHitObjectEXT = 5313,
    ReorderThreadWithHintEXT = 5314,
    ReorderThreadWithHitObjectEXT = 5315,
    HitObjectTraceRayEXT = 5316,
    HitObjectTraceRayMotionEXT = 5317,
    HitObjectRecordEmptyEXT = 5318,
    HitObjectExecuteShaderEXT = 5319,
    HitObjectGetCurrentTimeEXT = 5320,
    HitObjectGetAttributesEXT = 5321,
    HitObjectGetHitKindEXT = 5322,
    HitObjectGetPrimitiveIndexEXT = 5323,
    HitObjectGetGeometryIndexEXT = 5324,
    HitObjectGetInstanceIdEXT = 5325,
    HitObjectGetInstanceCustomIndexEXT = 5326,
    HitObjectGetObjectRayOriginEXT = 5327,
    HitObjectGetObjectRayDirectionEXT = 5328,
    HitObjectGetWorldRayDirectionEXT = 5329,
    HitObjectGetWorldRayOriginEXT = 5330,
    HitObjectGetObjectToWorldEXT = 5331,
    HitObjectGetWorldToObjectEXT = 5332,
    HitObjectGetRayTMaxEXT = 5333,
    ReportIntersectionKHR = 5334,
    ReportIntersectionNV = 5334,
    IgnoreIntersectionNV = 5335,
    TerminateRayNV = 5336,
    TraceNV = 5337,
    TraceMotionNV = 5338,
    TraceRayMotionNV = 5339,
    RayQueryGetIntersectionTriangleVertexPositionsKHR = 5340,
    TypeAccelerationStructureKHR = 5341,
    TypeAccelerationStructureNV = 5341,
    ExecuteCallableNV = 5344,
    RayQueryGetClusterIdNV = 5345,
    RayQueryGetIntersectionClusterIdNV = 5345,
    HitObjectGetClusterIdNV = 5346,
    HitObjectGetRayTMinEXT = 5347,
    HitObjectGetShaderBindingTableRecordIndexEXT = 5348,
    HitObjectGetShaderRecordBufferHandleEXT = 5349,
    HitObjectIsEmptyEXT = 5350,
    HitObjectIsHitEXT = 5351,
    HitObjectIsMissEXT = 5352,
    TypeCooperativeMatrixNV = 5358,
    CooperativeMatrixLoadNV = 5359,
    CooperativeMatrixStoreNV = 5360,
    CooperativeMatrixMulAddNV = 5361,
    CooperativeMatrixLengthNV = 5362,
    BeginInvocationInterlockEXT = 5364,
    EndInvocationInterlockEXT = 5365,
    CooperativeMatrixReduceNV = 5366,
    CooperativeMatrixLoadTensorNV = 5367,
    CooperativeMatrixStoreTensorNV = 5368,
    CooperativeMatrixPerElementOpNV = 5369,
    TypeTensorLayoutNV = 5370,
    TypeTensorViewNV = 5371,
    CreateTensorLayoutNV = 5372,
    TensorLayoutSetDimensionNV = 5373,
    TensorLayoutSetStrideNV = 5374,
    TensorLayoutSliceNV = 5375,
    TensorLayoutSetClampValueNV = 5376,
    CreateTensorViewNV = 5377,
    TensorViewSetDimensionNV = 5378,
    TensorViewSetStrideNV = 5379,
    DemoteToHelperInvocation = 5380,
    DemoteToHelperInvocationEXT = 5380,
    IsHelperInvocationEXT = 5381,
    TensorViewSetClipNV = 5382,
    TensorLayoutSetBlockSizeNV = 5384,
    CooperativeMatrixTransposeNV = 5390,
    ConvertUToImageNV = 5391,
    ConvertUToSamplerNV = 5392,
    ConvertImageToUNV = 5393,
    ConvertSamplerToUNV = 5394,
    ConvertUToSampledImageNV = 5395,
    ConvertSampledImageToUNV = 5396,
    SamplerImageAddressingModeNV = 5397,
    RawAccessChainNV = 5398,
    RayQueryGetIntersectionSpherePositionNV = 5427,
    RayQueryGetIntersectionSphereRadiusNV = 5428,
    RayQueryGetIntersectionLSSPositionsNV = 5429,
    RayQueryGetIntersectionLSSRadiiNV = 5430,
    RayQueryGetIntersectionLSSHitValueNV = 5431,
    HitObjectGetSpherePositionNV = 5432,
    HitObjectGetSphereRadiusNV = 5433,
    HitObjectGetLSSPositionsNV = 5434,
    HitObjectGetLSSRadiiNV = 5435,
    HitObjectIsSphereHitNV = 5436,
    HitObjectIsLSSHitNV = 5437,
    RayQueryIsSphereHitNV = 5438,
    RayQueryIsLSSHitNV = 5439,
    SubgroupShuffleINTEL = 5571,
    SubgroupShuffleDownINTEL = 5572,
    SubgroupShuffleUpINTEL = 5573,
    SubgroupShuffleXorINTEL = 5574,
    SubgroupBlockReadINTEL = 5575,
    SubgroupBlockWriteINTEL = 5576,
    SubgroupImageBlockReadINTEL = 5577,
    SubgroupImageBlockWriteINTEL = 5578,
    SubgroupImageMediaBlockReadINTEL = 5580,
    SubgroupImageMediaBlockWriteINTEL = 5581,
    UCountLeadingZerosINTEL = 5585,
    UCountTrailingZerosINTEL = 5586,
    AbsISubINTEL = 5587,
    AbsUSubINTEL = 5588,
    IAddSatINTEL = 5589,
    UAddSatINTEL = 5590,
    IAverageINTEL = 5591,
    UAverageINTEL = 5592,
    IAverageRoundedINTEL = 5593,
    UAverageRoundedINTEL = 5594,
    ISubSatINTEL = 5595,
    USubSatINTEL = 5596,
    IMul32x16INTEL = 5597,
    UMul32x16INTEL = 5598,
    ConstantFunctionPointerINTEL = 5600,
    FunctionPointerCallINTEL = 5601,
    AsmTargetINTEL = 5609,
    AsmINTEL = 5610,
    AsmCallINTEL = 5611,
    AtomicFMinEXT = 5614,
    AtomicFMaxEXT = 5615,
    AssumeTrueKHR = 5630,
    ExpectKHR = 5631,
    DecorateString = 5632,
    DecorateStringGOOGLE = 5632,
    MemberDecorateString = 5633,
    MemberDecorateStringGOOGLE = 5633,
    VmeImageINTEL = 5699,
    TypeVmeImageINTEL = 5700,
    TypeAvcImePayloadINTEL = 5701,
    TypeAvcRefPayloadINTEL = 5702,
    TypeAvcSicPayloadINTEL = 5703,
    TypeAvcMcePayloadINTEL = 5704,
    TypeAvcMceResultINTEL = 5705,
    TypeAvcImeResultINTEL = 5706,
    TypeAvcImeResultSingleReferenceStreamoutINTEL = 5707,
    TypeAvcImeResultDualReferenceStreamoutINTEL = 5708,
    TypeAvcImeSingleReferenceStreaminINTEL = 5709,
    TypeAvcImeDualReferenceStreaminINTEL = 5710,
    TypeAvcRefResultINTEL = 5711,
    TypeAvcSicResultINTEL = 5712,
    SubgroupAvcMceGetDefaultInterBaseMultiReferencePenaltyINTEL = 5713,
    SubgroupAvcMceSetInterBaseMultiReferencePenaltyINTEL = 5714,
    SubgroupAvcMceGetDefaultInterShapePenaltyINTEL = 5715,
    SubgroupAvcMceSetInterShapePenaltyINTEL = 5716,
    SubgroupAvcMceGetDefaultInterDirectionPenaltyINTEL = 5717,
    SubgroupAvcMceSetInterDirectionPenaltyINTEL = 5718,
    SubgroupAvcMceGetDefaultIntraLumaShapePenaltyINTEL = 5719,
    SubgroupAvcMceGetDefaultInterMotionVectorCostTableINTEL = 5720,
    SubgroupAvcMceGetDefaultHighPenaltyCostTableINTEL = 5721,
    SubgroupAvcMceGetDefaultMediumPenaltyCostTableINTEL = 5722,
    SubgroupAvcMceGetDefaultLowPenaltyCostTableINTEL = 5723,
    SubgroupAvcMceSetMotionVectorCostFunctionINTEL = 5724,
    SubgroupAvcMceGetDefaultIntraLumaModePenaltyINTEL = 5725,
    SubgroupAvcMceGetDefaultNonDcLumaIntraPenaltyINTEL = 5726,
    SubgroupAvcMceGetDefaultIntraChromaModeBasePenaltyINTEL = 5727,
    SubgroupAvcMceSetAcOnlyHaarINTEL = 5728,
    SubgroupAvcMceSetSourceInterlacedFieldPolarityINTEL = 5729,
    SubgroupAvcMceSetSingleReferenceInterlacedFieldPolarityINTEL = 5730,
    SubgroupAvcMceSetDualReferenceInterlacedFieldPolaritiesINTEL = 5731,
    SubgroupAvcMceConvertToImePayloadINTEL = 5732,
    SubgroupAvcMceConvertToImeResultINTEL = 5733,
    SubgroupAvcMceConvertToRefPayloadINTEL = 5734,
    SubgroupAvcMceConvertToRefResultINTEL = 5735,
    SubgroupAvcMceConvertToSicPayloadINTEL = 5736,
    SubgroupAvcMceConvertToSicResultINTEL = 5737,
    SubgroupAvcMceGetMotionVectorsINTEL = 5738,
    SubgroupAvcMceGetInterDistortionsINTEL = 5739,
    SubgroupAvcMceGetBestInterDistortionsINTEL = 5740,
    SubgroupAvcMceGetInterMajorShapeINTEL = 5741,
    SubgroupAvcMceGetInterMinorShapeINTEL = 5742,
    SubgroupAvcMceGetInterDirectionsINTEL = 5743,
    SubgroupAvcMceGetInterMotionVectorCountINTEL = 5744,
    SubgroupAvcMceGetInterReferenceIdsINTEL = 5745,
    SubgroupAvcMceGetInterReferenceInterlacedFieldPolaritiesINTEL = 5746,
    SubgroupAvcImeInitializeINTEL = 5747,
    SubgroupAvcImeSetSingleReferenceINTEL = 5748,
    SubgroupAvcImeSetDualReferenceINTEL = 5749,
    SubgroupAvcImeRefWindowSizeINTEL = 5750,
    SubgroupAvcImeAdjustRefOffsetINTEL = 5751,
    SubgroupAvcImeConvertToMcePayloadINTEL = 5752,
    SubgroupAvcImeSetMaxMotionVectorCountINTEL = 5753,
    SubgroupAvcImeSetUnidirectionalMixDisableINTEL = 5754,
    SubgroupAvcImeSetEarlySearchTerminationThresholdINTEL = 5755,
    SubgroupAvcImeSetWeightedSadINTEL = 5756,
    SubgroupAvcImeEvaluateWithSingleReferenceINTEL = 5757,
    SubgroupAvcImeEvaluateWithDualReferenceINTEL = 5758,
    SubgroupAvcImeEvaluateWithSingleReferenceStreaminINTEL = 5759,
    SubgroupAvcImeEvaluateWithDualReferenceStreaminINTEL = 5760,
    SubgroupAvcImeEvaluateWithSingleReferenceStreamoutINTEL = 5761,
    SubgroupAvcImeEvaluateWithDualReferenceStreamoutINTEL = 5762,
    SubgroupAvcImeEvaluateWithSingleReferenceStreaminoutINTEL = 5763,
    SubgroupAvcImeEvaluateWithDualReferenceStreaminoutINTEL = 5764,
    SubgroupAvcImeConvertToMceResultINTEL = 5765,
    SubgroupAvcImeGetSingleReferenceStreaminINTEL = 5766,
    SubgroupAvcImeGetDualReferenceStreaminINTEL = 5767,
    SubgroupAvcImeStripSingleReferenceStreamoutINTEL = 5768,
    SubgroupAvcImeStripDualReferenceStreamoutINTEL = 5769,
    SubgroupAvcImeGetStreamoutSingleReferenceMajorShapeMotionVectorsINTEL = 5770,
    SubgroupAvcImeGetStreamoutSingleReferenceMajorShapeDistortionsINTEL = 5771,
    SubgroupAvcImeGetStreamoutSingleReferenceMajorShapeReferenceIdsINTEL = 5772,
    SubgroupAvcImeGetStreamoutDualReferenceMajorShapeMotionVectorsINTEL = 5773,
    SubgroupAvcImeGetStreamoutDualReferenceMajorShapeDistortionsINTEL = 5774,
    SubgroupAvcImeGetStreamoutDualReferenceMajorShapeReferenceIdsINTEL = 5775,
    SubgroupAvcImeGetBorderReachedINTEL = 5776,
    SubgroupAvcImeGetTruncatedSearchIndicationINTEL = 5777,
    SubgroupAvcImeGetUnidirectionalEarlySearchTerminationINTEL = 5778,
    SubgroupAvcImeGetWeightingPatternMinimumMotionVectorINTEL = 5779,
    SubgroupAvcImeGetWeightingPatternMinimumDistortionINTEL = 5780,
    SubgroupAvcFmeInitializeINTEL = 5781,
    SubgroupAvcBmeInitializeINTEL = 5782,
    SubgroupAvcRefConvertToMcePayloadINTEL = 5783,
    SubgroupAvcRefSetBidirectionalMixDisableINTEL = 5784,
    SubgroupAvcRefSetBilinearFilterEnableINTEL = 5785,
    SubgroupAvcRefEvaluateWithSingleReferenceINTEL = 5786,
    SubgroupAvcRefEvaluateWithDualReferenceINTEL = 5787,
    SubgroupAvcRefEvaluateWithMultiReferenceINTEL = 5788,
    SubgroupAvcRefEvaluateWithMultiReferenceInterlacedINTEL = 5789,
    SubgroupAvcRefConvertToMceResultINTEL = 5790,
    SubgroupAvcSicInitializeINTEL = 5791,
    SubgroupAvcSicConfigureSkcINTEL = 5792,
    SubgroupAvcSicConfigureIpeLumaINTEL = 5793,
    SubgroupAvcSicConfigureIpeLumaChromaINTEL = 5794,
    SubgroupAvcSicGetMotionVectorMaskINTEL = 5795,
    SubgroupAvcSicConvertToMcePayloadINTEL = 5796,
    SubgroupAvcSicSetIntraLumaShapePenaltyINTEL = 5797,
    SubgroupAvcSicSetIntraLumaModeCostFunctionINTEL = 5798,
    SubgroupAvcSicSetIntraChromaModeCostFunctionINTEL = 5799,
    SubgroupAvcSicSetBilinearFilterEnableINTEL = 5800,
    SubgroupAvcSicSetSkcForwardTransformEnableINTEL = 5801,
    SubgroupAvcSicSetBlockBasedRawSkipSadINTEL = 5802,
    SubgroupAvcSicEvaluateIpeINTEL = 5803,
    SubgroupAvcSicEvaluateWithSingleReferenceINTEL = 5804,
    SubgroupAvcSicEvaluateWithDualReferenceINTEL = 5805,
    SubgroupAvcSicEvaluateWithMultiReferenceINTEL = 5806,
    SubgroupAvcSicEvaluateWithMultiReferenceInterlacedINTEL = 5807,
    SubgroupAvcSicConvertToMceResultINTEL = 5808,
    SubgroupAvcSicGetIpeLumaShapeINTEL = 5809,
    SubgroupAvcSicGetBestIpeLumaDistortionINTEL = 5810,
    SubgroupAvcSicGetBestIpeChromaDistortionINTEL = 5811,
    SubgroupAvcSicGetPackedIpeLumaModesINTEL = 5812,
    SubgroupAvcSicGetIpeChromaModeINTEL = 5813,
    SubgroupAvcSicGetPackedSkcLumaCountThresholdINTEL = 5814,
    SubgroupAvcSicGetPackedSkcLumaSumThresholdINTEL = 5815,
    SubgroupAvcSicGetInterRawSadsINTEL = 5816,
    VariableLengthArrayINTEL = 5818,
    SaveMemoryINTEL = 5819,
    RestoreMemoryINTEL = 5820,
    ArbitraryFloatSinCosPiALTERA = 5840,
    ArbitraryFloatSinCosPiINTEL = 5840,
    ArbitraryFloatCastALTERA = 5841,
    ArbitraryFloatCastINTEL = 5841,
    ArbitraryFloatCastFromIntALTERA = 5842,
    ArbitraryFloatCastFromIntINTEL = 5842,
    ArbitraryFloatCastToIntALTERA = 5843,
    ArbitraryFloatCastToIntINTEL = 5843,
    ArbitraryFloatAddALTERA = 5846,
    ArbitraryFloatAddINTEL = 5846,
    ArbitraryFloatSubALTERA = 5847,
    ArbitraryFloatSubINTEL = 5847,
    ArbitraryFloatMulALTERA = 5848,
    ArbitraryFloatMulINTEL = 5848,
    ArbitraryFloatDivALTERA = 5849,
    ArbitraryFloatDivINTEL = 5849,
    ArbitraryFloatGTALTERA = 5850,
    ArbitraryFloatGTINTEL = 5850,
    ArbitraryFloatGEALTERA = 5851,
    ArbitraryFloatGEINTEL = 5851,
    ArbitraryFloatLTALTERA = 5852,
    ArbitraryFloatLTINTEL = 5852,
    ArbitraryFloatLEALTERA = 5853,
    ArbitraryFloatLEINTEL = 5853,
    ArbitraryFloatEQALTERA = 5854,
    ArbitraryFloatEQINTEL = 5854,
    ArbitraryFloatRecipALTERA = 5855,
    ArbitraryFloatRecipINTEL = 5855,
    ArbitraryFloatRSqrtALTERA = 5856,
    ArbitraryFloatRSqrtINTEL = 5856,
    ArbitraryFloatCbrtALTERA = 5857,
    ArbitraryFloatCbrtINTEL = 5857,
    ArbitraryFloatHypotALTERA = 5858,
    ArbitraryFloatHypotINTEL = 5858,
    ArbitraryFloatSqrtALTERA = 5859,
    ArbitraryFloatSqrtINTEL = 5859,
    ArbitraryFloatLogINTEL = 5860,
    ArbitraryFloatLog2INTEL = 5861,
    ArbitraryFloatLog10INTEL = 5862,
    ArbitraryFloatLog1pINTEL = 5863,
    ArbitraryFloatExpINTEL = 5864,
    ArbitraryFloatExp2INTEL = 5865,
    ArbitraryFloatExp10INTEL = 5866,
    ArbitraryFloatExpm1INTEL = 5867,
    ArbitraryFloatSinINTEL = 5868,
    ArbitraryFloatCosINTEL = 5869,
    ArbitraryFloatSinCosINTEL = 5870,
    ArbitraryFloatSinPiINTEL = 5871,
    ArbitraryFloatCosPiINTEL = 5872,
    ArbitraryFloatASinINTEL = 5873,
    ArbitraryFloatASinPiINTEL = 5874,
    ArbitraryFloatACosINTEL = 5875,
    ArbitraryFloatACosPiINTEL = 5876,
    ArbitraryFloatATanINTEL = 5877,
    ArbitraryFloatATanPiINTEL = 5878,
    ArbitraryFloatATan2INTEL = 5879,
    ArbitraryFloatPowINTEL = 5880,
    ArbitraryFloatPowRINTEL = 5881,
    ArbitraryFloatPowNINTEL = 5882,
    LoopControlINTEL = 5887,
    AliasDomainDeclINTEL = 5911,
    AliasScopeDeclINTEL = 5912,
    AliasScopeListDeclINTEL = 5913,
    FixedSqrtALTERA = 5923,
    FixedSqrtINTEL = 5923,
    FixedRecipALTERA = 5924,
    FixedRecipINTEL = 5924,
    FixedRsqrtALTERA = 5925,
    FixedRsqrtINTEL = 5925,
    FixedSinALTERA = 5926,
    FixedSinINTEL = 5926,
    FixedCosALTERA = 5927,
    FixedCosINTEL = 5927,
    FixedSinCosALTERA = 5928,
    FixedSinCosINTEL = 5928,
    FixedSinPiALTERA = 5929,
    FixedSinPiINTEL = 5929,
    FixedCosPiALTERA = 5930,
    FixedCosPiINTEL = 5930,
    FixedSinCosPiALTERA = 5931,
    FixedSinCosPiINTEL = 5931,
    FixedLogALTERA = 5932,
    FixedLogINTEL = 5932,
    FixedExpALTERA = 5933,
    FixedExpINTEL = 5933,
    PtrCastToCrossWorkgroupALTERA = 5934,
    PtrCastToCrossWorkgroupINTEL = 5934,
    CrossWorkgroupCastToPtrALTERA = 5938,
    CrossWorkgroupCastToPtrINTEL = 5938,
    ReadPipeBlockingALTERA = 5946,
    ReadPipeBlockingINTEL = 5946,
    WritePipeBlockingALTERA = 5947,
    WritePipeBlockingINTEL = 5947,
    FPGARegALTERA = 5949,
    FPGARegINTEL = 5949,
    RayQueryGetRayTMinKHR = 6016,
    RayQueryGetRayFlagsKHR = 6017,
    RayQueryGetIntersectionTKHR = 6018,
    RayQueryGetIntersectionInstanceCustomIndexKHR = 6019,
    RayQueryGetIntersectionInstanceIdKHR = 6020,
    RayQueryGetIntersectionInstanceShaderBindingTableRecordOffsetKHR = 6021,
    RayQueryGetIntersectionGeometryIndexKHR = 6022,
    RayQueryGetIntersectionPrimitiveIndexKHR = 6023,
    RayQueryGetIntersectionBarycentricsKHR = 6024,
    RayQueryGetIntersectionFrontFaceKHR = 6025,
    RayQueryGetIntersectionCandidateAABBOpaqueKHR = 6026,
    RayQueryGetIntersectionObjectRayDirectionKHR = 6027,
    RayQueryGetIntersectionObjectRayOriginKHR = 6028,
    RayQueryGetWorldRayDirectionKHR = 6029,
    RayQueryGetWorldRayOriginKHR = 6030,
    RayQueryGetIntersectionObjectToWorldKHR = 6031,
    RayQueryGetIntersectionWorldToObjectKHR = 6032,
    AtomicFAddEXT = 6035,
    TypeBufferSurfaceINTEL = 6086,
    TypeStructContinuedINTEL = 6090,
    ConstantCompositeContinuedINTEL = 6091,
    SpecConstantCompositeContinuedINTEL = 6092,
    CompositeConstructContinuedINTEL = 6096,
    ConvertFToBF16INTEL = 6116,
    ConvertBF16ToFINTEL = 6117,
    ControlBarrierArriveEXT = 6142,
    ControlBarrierArriveINTEL = 6142,
    ControlBarrierWaitEXT = 6143,
    ControlBarrierWaitINTEL = 6143,
    ArithmeticFenceEXT = 6145,
    TaskSequenceCreateALTERA = 6163,
    TaskSequenceCreateINTEL = 6163,
    TaskSequenceAsyncALTERA = 6164,
    TaskSequenceAsyncINTEL = 6164,
    TaskSequenceGetALTERA = 6165,
    TaskSequenceGetINTEL = 6165,
    TaskSequenceReleaseALTERA = 6166,
    TaskSequenceReleaseINTEL = 6166,
    TypeTaskSequenceALTERA = 6199,
    TypeTaskSequenceINTEL = 6199,
    SubgroupBlockPrefetchINTEL = 6221,
    Subgroup2DBlockLoadINTEL = 6231,
    Subgroup2DBlockLoadTransformINTEL = 6232,
    Subgroup2DBlockLoadTransposeINTEL = 6233,
    Subgroup2DBlockPrefetchINTEL = 6234,
    Subgroup2DBlockStoreINTEL = 6235,
    SubgroupMatrixMultiplyAccumulateINTEL = 6237,
    BitwiseFunctionINTEL = 6242,
    UntypedVariableLengthArrayINTEL = 6244,
    ConditionalExtensionINTEL = 6248,
    ConditionalEntryPointINTEL = 6249,
    ConditionalCapabilityINTEL = 6250,
    SpecConstantTargetINTEL = 6251,
    SpecConstantArchitectureINTEL = 6252,
    SpecConstantCapabilitiesINTEL = 6253,
    ConditionalCopyObjectINTEL = 6254,
    PredicatedLoadINTEL = 6258,
    PredicatedStoreINTEL = 6259,
    GroupIMulKHR = 6401,
    GroupFMulKHR = 6402,
    GroupBitwiseAndKHR = 6403,
    GroupBitwiseOrKHR = 6404,
    GroupBitwiseXorKHR = 6405,
    GroupLogicalAndKHR = 6406,
    GroupLogicalOrKHR = 6407,
    GroupLogicalXorKHR = 6408,
    RoundFToTF32INTEL = 6426,
    MaskedGatherINTEL = 6428,
    MaskedScatterINTEL = 6429,
    ConvertHandleToImageINTEL = 6529,
    ConvertHandleToSamplerINTEL = 6530,
    ConvertHandleToSampledImageINTEL = 6531,
    FDot2MixAcc32VALVE = 6916,
    FDot2MixAcc16VALVE = 6917,
    FDot4MixAcc32VALVE = 6918,
    Max = 0x7fffffff,
}