#+vet explicit-allocators !unused-procedures
package main

import "base:runtime"

import "core:fmt"
import "core:os"
import "core:strings"

import vk "../lib/vulkan"

Shader_Info :: struct {
    source: Watcher_Id,
    common: Watcher_Id,
}

Shader :: struct {
    was_modified: bool,
    bytes:      [] u8,
    stage:      vk.ShaderStageFlag,
    local_size: uv3,
}

/*
    simple struct: 
        A type that is used inside buffers, or as a value.
    
    buffer reference struct:
        A type that is passed to shader via a pointer, and which may contain pointers to buffers.
        
        These pointers must be vk.DeviceAddress types on the cpu side and must contain a tag like:
            field_name: vk.DeviceAddress "name_of_the_pointed_at_type"
            (The tag's "name_of_the_pointed_at_type" must be the type name used in the shader.)
        
*/

generate_shader_api :: proc (output_file: string) {
    builder := strings.builder_make(context.temp_allocator)
    
    // :Shader: all types used by the cpu and the gpu
    
    // structs used in buffers
    append_simple_struct(&builder, Draw_Command)
    append_simple_struct(&builder, Draw)
    append_simple_struct(&builder, Mesh_LOD)
    append_simple_struct(&builder, Mesh)
    append_simple_struct(&builder, Meshlet)
    append_simple_struct(&builder, Vertex)
    append_simple_struct(&builder, UI_Draw)
    
    reference_types := make(map[string] struct {}, context.temp_allocator)
    simple_types    := make(map[typeid] struct {}, context.temp_allocator)
    
    // anything with a vk.DeviceAddress member
    collect_types(&simple_types, &reference_types, Draw_Data)
    collect_types(&simple_types, &reference_types, Depth_Data)
    collect_types(&simple_types, &reference_types, UI_Data)
    reference_types["uint8_t"] = {}
    append_reference_types(&builder, reference_types)
    
    // nested structs
    for simple_type, _ in simple_types {
        append_simple_struct(&builder, simple_type)
    }
    
    // push constants
    append_buffer_reference_struct(&builder, Draw_Data)
    append_buffer_reference_struct(&builder, Depth_Data)
    append_buffer_reference_struct(&builder, UI_Data)
    
    ////////////////////////////////////////////////
    // implementation
    
    get_type_name :: proc (info: ^runtime.Type_Info) -> (string, string) {
        type_name: string
        array_string: string
        
        switch info.id {
        case f32: type_name = "float"
        
        case u32: type_name = "uint"
        case i8:  type_name = "int8_t"
        case u8:  type_name = "uint8_t"
        case u16: type_name = "uint16_t"
        case i16: type_name = "int16_t"
        
        case b8:  type_name = "uint8_t"
        case uv3: type_name = "uvec3"
        case hv2: type_name = "uint /* hvec2 */"
        
        case v2: type_name = "vec2"
        case v3: type_name = "vec3"
        case v4: type_name = "vec4"
        case m4: type_name = "mat4"
        
        case q32:        type_name = "vec4"
        case Rectangle2: type_name = "vec4"
        case b32:        type_name = "bool"
        
        case: 
            if array_type, ok := info.variant.(runtime.Type_Info_Array); ok {
                array_string = fmt.tprintf("[%v]", array_type.count)
                type_name = fmt.tprintf("%v%v", get_type_name(array_type.elem))
            } else {
                type_name = fmt.tprint(info.id)
            }
        }
        
        return type_name, array_string
    }
    
    append_location :: proc (builder: ^strings.Builder, loc := #caller_location) {
        fmt.sbprintf(builder, "// @generated by %v\n", loc)
    }
    
    append_simple_struct :: proc (builder: ^strings.Builder, type: typeid, loc := #caller_location) {
        append_location(builder, loc)
        
        fmt.sbprintf(builder, "struct %v {{\n", type)
        
        append_struct_fields(builder, type)
        
        fmt.sbprintf(builder, "};\n\n")
    }
    
    collect_types :: proc (simples: ^map[typeid] struct {}, references: ^map[string] struct {}, type: typeid) {
        info := type_info_of(runtime.typeid_base(type))
        s :=  info.variant.(runtime.Type_Info_Struct)
        
        for field in soa_zip(info = s.types[:s.field_count], tag = s.tags[:s.field_count]) {
            field_info := field.info
            id := field_info.id
            field_base_info := type_info_of(runtime.typeid_base(id))
            
            if field.tag != "" && id == typeid_of(vk.DeviceAddress) {
                references[field.tag] = {}
            } else if _, is_struct := field_base_info.variant.(runtime.Type_Info_Struct); is_struct {
                simples[field_info.id] = {}
            }
        }
    }
    
    append_reference_types :: proc (builder: ^strings.Builder, refs: map[string] struct{}, loc := #caller_location) {
        append_location(builder, loc)
        
        for type_name, _ in refs {
            alignment := 4 // @todo unhardcode the alignment once we know the inner type
            if type_name == "uint8_t" { alignment = 1 } // @hack
            fmt.sbprintf(builder, "layout(buffer_reference, buffer_reference_align = %v, std430, scalar) buffer %v_p {{ %v v; };\n", alignment, type_name, type_name)
        }
        fmt.sbprintf(builder, "\n")
    }
    
    append_buffer_reference_struct :: proc (builder: ^strings.Builder, type: typeid, loc := #caller_location) {
        append_location(builder, loc)
        
        fmt.sbprintf(builder, "layout(buffer_reference, buffer_reference_align = %v, std430, scalar) ", align_of(pmm))
        fmt.sbprintf(builder, "buffer %v {{\n", type)
        
        append_struct_fields(builder, type)
        fmt.sbprintf(builder, "};\n\n")
    }
    
    append_struct_fields :: proc (builder: ^strings.Builder, type: typeid) {
        info := type_info_of(runtime.typeid_base(type))
        s :=  info.variant.(runtime.Type_Info_Struct)
        
        for field in soa_zip(type = s.types[:s.field_count], name = s.names[:s.field_count], tag = s.tags[:s.field_count]) {
            if field.tag != "" {
                type := field.tag
                fmt.sbprintf(builder, "    %v_p %v;\n", type, field.name)
                continue
            }
            
            type_name, array_string := get_type_name(field.type)
            fmt.sbprintf(builder, "    %v %v%v;\n", type_name, field.name, array_string)
        }
    }
    
    error := os.write_entire_file(output_file, strings.to_string(builder))
    if error != nil {
        assert(false, fmt.tprintfln("Failed to generate shader api file `%v`: %v", output_file, error))
    }
}

init_shader_and_watchers :: proc (watchers: ^Watchers, common_watcher: Watcher_Id, input: string, output_extension := ".spv") -> Shader_Id {
    id, info := make_shader()
    
    info.source = watchers_make(watchers, input)
    info.common = common_watcher
    
    watcher_depend_on(watchers, info.common)
    watcher_depend_on(watchers, info.source)
    
    return id
}

recompile_shaders_if_needed :: proc (watchers: ^Watchers, shaders_ids: ..Shader_Id) {
    for id in shaders_ids {
        info := get_shader_info(id)^
        
        needs_recompile: bool
        // @study does this prevent "early return" optimizations that would cause the second check to 
        // be skipped, if the first one is already true? If not then we will recompile once for the 
        // source and once for the header if both are modified at once, because we optimistically skip
        // the second check.
        needs_recompile ||= watcher_check_and_reset(watchers, info.source)
        needs_recompile ||= watcher_check_and_reset(watchers, info.common)
        
        if needs_recompile {
            shader := get_shader(id, immediately = false)
            compile_shader(id, watchers[info.source].path, old_bytes = shader.bytes)
        }
    }
}

compile_shader :: proc (id: Shader_Id, input_path: string, output_directory := "build", output_extension := ".spv", old_bytes: [] u8 = nil) {
    cmd: Cmd
    cmd.allocator = context.temp_allocator
    
    input_directory, input_file := os.split_path(input_path)
    
    output_path, _ := os.join_path({input_directory, output_directory, input_file}, context.temp_allocator)
    shader_output := fmt.tprintf("%v%v", output_path, output_extension)
    
    compile_shader_begin(&cmd, shader_output)
    
    // embed shader source code for renderdoc
    if ODIN_DEBUG { append(&cmd, "-g") }
    if Optimized  { append(&cmd, "-O") }
    
    append(&cmd, input_path)
    
    procs, comp, comp_allocator := make_shader_compilation()
    comp^ = {
        false,
        id,
        strings.clone(input_path,    comp_allocator),
        strings.clone(shader_output, comp_allocator),
        old_bytes,
    }
    
    if !run_command(&cmd, or_exit = false, stdout = os.stdout, stderr = os.stderr, async = procs) {
        assert(false, "Failing to run the command means that it is faulty.")
    }
}

parse_shader :: proc (shader: ^Shader) {
    if shader.bytes == nil { return }
    
    shader_code := slice_from_parts(u32, raw_data(shader.bytes), len(shader.bytes) / 4)
    
    assert(shader_code[0] == SpvMagicNumber)
    id_bound := shader_code[3]
    
    Id :: struct {
        opcode:   SpvOp,
        constant: u32,
    }
    
    ////////////////////////////////////////////////
    // copy-pasted from https://github.com/KhronosGroup/SPIRV-Headers/blob/main/include/spirv/unified1/spirv.h
    
    SpvMagicNumber :: 0x07230203
    
    SpvExecutionMode :: enum  u32 {
        LocalSize = 17,
        LocalSizeId = 38,
        // all other values were omitted
    }
    
    SpvExecutionModel :: enum u32 { 
        Vertex = 0,
        Fragment = 4,
        GLCompute = 5,
        TaskEXT = 5364,
        MeshEXT = 5365,
        // all other values were omitted
    }
    
    SpvOp:: enum u32 {
        EntryPoint = 15,
        ExecutionMode = 16,
        Constant = 43,
        ExecutionModeId = 331,
        // all other values were omitted
    }
    
    ////////////////////////////////////////////////
    
    ids := make([] Id, id_bound, context.temp_allocator)
    
    code := shader_code[5:]
    
    local_size: [3] i32 = -1
    
    for len(code) != 0 {
        opcode     := cast(SpvOp) cast(u16) ((code[0] >>  0) & 0xFFFF)
        word_count := cast(u16) ((code[0] >> 16) & 0xFFFF)
        
        #partial switch opcode {
            case .EntryPoint:
                execution_model := cast(SpvExecutionModel) code[1]
                
                #partial switch execution_model {
                    case .Vertex:     shader.stage = .VERTEX
                    case .Fragment:   shader.stage = .FRAGMENT
                    case .MeshEXT:    shader.stage = .MESH_EXT
                    case .TaskEXT:    shader.stage = .TASK_EXT
                    case .GLCompute:  shader.stage = .COMPUTE
                }
                
                case .ExecutionMode:
                    mode := cast(SpvExecutionMode) code[2]
                    if mode == .LocalSize {
                        shader.local_size = { code[3], code[4], code[5] }
                    }
                    
                    case .ExecutionModeId:
                        mode := cast(SpvExecutionMode) code[2]
                        if mode == .LocalSizeId {
                            local_size = { cast(i32) code[3], cast(i32) code[4], cast(i32) code[5] }
                        }
                        
                        case .Constant:
                            id := code[2]
                            assert(ids[id].opcode == {})
                            
                            ids[id].opcode   = opcode
                            ids[id].constant = code[3]
                        }
                        
                        code = code[word_count:]
                    }
                    
                    if shader.stage == .COMPUTE {
                        for it in 0..<3 {
                            if local_size[it] >= 0 {
                                assert(ids[local_size[it]].opcode == .Constant)
                                shader.local_size[it] = ids[local_size[it]].constant
                            }
                        }
                        
                        assert(shader.local_size != 0)
                    }
}

compile_shader_begin :: proc (cmd: ^Cmd, shader_output: string) {
    append(cmd, "glslc.exe")
    append(cmd, "--target-env=vulkan1.4")
    append(cmd, "-o", shader_output)
}

shader_grid_dimension_from_total_count :: proc (shader: ^Shader, x: u32 = 1, y: u32 = 1, z: u32 = 1) -> uv3 {
    total_count := uv3 { x, y, z }
    result := (total_count + shader.local_size-1) / shader.local_size
    return result
}

////////////////////////////////////////////////
// @copypasta from build utility procs

Procs :: [dynamic] os.Process
Cmd   :: [dynamic] string

Command_Console :: union {
    ^string,
    ^os.File,
}

run_command :: proc (cmd: ^Cmd, or_exit := true, keep := false, stdout: Command_Console = nil, stderr: Command_Console = nil, async: ^Procs = nil) -> (success: bool) {
    fmt.printf("CMD: %v\n", strings.join(cmd[:], " ", context.temp_allocator))
    
    process_description := os.Process_Desc { command = cmd[:] }
    process: os.Process
    state:   os.Process_State
	output:  [] byte
	error:   [] byte
    err2:    os.Error
    
    if async == nil {
        _, out_is_file := stdout.(^os.File)
        assert(!out_is_file, "synchronous execution already captures the output, so it can't we written to a file by the process itself")
        _, err_is_file := stdout.(^os.File)
        assert(!err_is_file, "synchronous execution already captures the output, so it can't we written to a file by the process itself")
        
        state, output, error, err2 = os.process_exec(process_description, context.allocator)
    } else {
        if err, ok := stderr.(^os.File); ok do process_description.stderr = err
        if out, ok := stdout.(^os.File); ok do process_description.stdout = out
        process, err2 = os.process_start(process_description)
        append(async, process)
    }
    
    if err2 != nil {
        fmt.printf("ERROR: Failed to run command: %v\n", err2)
        return false
    }
    
    if async == nil {
        if output != nil {
            switch out in stdout {
            case nil:      fmt.println(cast(string) output)
            case ^string:  out^ = cast(string) output
            case ^os.File: unreachable()
            }
        }
        
        if error != nil {
            switch out in stderr {
            case nil:      fmt.eprintln(cast(string) error)
            case ^string:  out^ = cast(string) error
            case ^os.File: unreachable()
            }
        }
        
        if or_exit && (!state.success || state.exit_code != 0) do os.exit(state.exit_code)
        
        success = state.success
    } else {
        success = true
    }
    
    if !keep do clear(cmd)
    
    return success
}