#version 460

#extension GL_EXT_shader_explicit_arithmetic_types_int64: require
#extension GL_EXT_control_flow_attributes: require
#extension GL_EXT_nonuniform_qualifier: require
#extension GL_EXT_descriptor_heap: require

#include "common.glsl"

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(constant_id = 0) const bool Late = true; // @todo when this defaults to false occlusion isnt toggleable, but when its true we can toggle it on and off

// @volatile
layout(push_constant) uniform Push_Data {
    Cull_Globals globals;
};

layout(descriptor_heap) uniform texture2D Textures[];
layout(descriptor_heap) uniform sampler   Samplers[];

////////////////////////////////////////////////

// Based on this paper: 
//     2D Polyhedral Bounds of a Clipped, Perspective-Projected 3D Sphere. Michael Mara, Morgan McGuire. 2013
//     https://jcgt.org/published/0002/02/05/paper.pdf
//     :ViewSpace: is used to simplify the original calculations down to this form
bool project_sphere_onto_screen(vec3 view_center, float radius, float p00, float p11, float near_z, out vec4 result) {
    if (view_center.z + radius > -near_z) { // :ViewSpace:
        return false;
    }
    
    // center in the x/y-z frame
    vec2 cx = -view_center.xz;
    vec2 cy = -view_center.yz;
    
    float cx_dot = dot(cx, cx);
    float cy_dot = dot(cy, cy);
    
    // (cos, sin) of angle theta between c and x/y tangent vector
    vec2 vx = vec2(sqrt(cx_dot - (radius * radius)), radius);
    vec2 vy = vec2(sqrt(cy_dot - (radius * radius)), radius);
    
    // In the x/y-z reference frame
    // Transform back to camera space
    float min_x = -p00 * dot(vec2(vx.x,  vx.y), cx) / dot(vec2(-vx.y, vx.x), cx);
    float max_x = -p00 * dot(vec2(vx.x, -vx.y), cx) / dot(vec2( vx.y, vx.x), cx);
    float min_y = p11 * dot(vec2(vy.x,  vy.y), cy) / dot(vec2(-vy.y, vy.x), cy);
    float max_y = p11 * dot(vec2(vy.x, -vy.y), cy) / dot(vec2( vy.y, vy.x), cy); 
    
    result = vec4(min_x, min_y, max_x, max_y);
    
    // transform to clip space
    result = result.xwzy * vec4(.5, -.5, .5, -.5) + .5;
    
    return true;
}

void main() {
    uint draw_index = gl_GlobalInvocationID.x;
    
    if (draw_index >= globals.data.draw_count) return;
    
    bool_p was_visible_last_frame = globals.draw_visibility_buffer[draw_index];
    if (!Late && !was_visible_last_frame.v) return;
    
    bool frustum_culling_enabled = (globals.data.flags & Flag_FrustumCulling)   != 0;
    bool lod_enabled             = (globals.data.flags & Flag_LevelOfDetail)    != 0;
    bool occlusion_enabled       = (globals.data.flags & Flag_OcclusionCulling) != 0;
    
    Draw_p draw               = globals.draw_buffer[draw_index];
    Mesh_p mesh               = globals.mesh_buffer[draw.v.mesh_index];
    uint_p draw_command_count = globals.draw_command_count;
    
    vec3  world_center = transform(draw.v.orientation, draw.v.scale, draw.v.p, mesh.v.center);
    float radius       = draw.v.scale * mesh.v.radius;
    
    vec4 view_center = globals.data.view_from_world * vec4(world_center, 1);
    // @todo scale radius by view_from_world?
    
    bool visible = true;
    if (frustum_culling_enabled) {
        // the left/top/right/bottom plane culling utilizes frustum symmetry to cull against two planes at the same time
        visible = visible && view_center.z * globals.data.frustum[1] - abs(view_center.x) * globals.data.frustum[0] > -radius;
        visible = visible && view_center.z * globals.data.frustum[3] - abs(view_center.y) * globals.data.frustum[2] > -radius;
        // the near/far plane culling uses camera space Z directly, but the camera looks down -z :ViewSpace:
        visible = visible && view_center.z + radius < -globals.data.near_z && view_center.z - radius > -globals.data.far_z;
    }
    
    if (Late && occlusion_enabled && visible) {
        vec4 rect;
        if (project_sphere_onto_screen(view_center.xyz, radius, globals.data.p00, globals.data.p11, globals.data.near_z, rect)) {
            vec2 size_in_pixels = (rect.zw - rect.xy) * globals.data.pyramid_size;
            
            float level = floor(log2(max(size_in_pixels.x, size_in_pixels.y)));
            vec2  rect_center = (rect.xy + rect.zw) * 0.5;
            
            float depth = textureLod(sampler2D(Textures[globals.depth_pyramid_index], Samplers[Sampler_Depth]), rect_center, level).x;
            float min_sphere_depth = -globals.data.near_z / (view_center.z + radius); // :ViewSpace:
            
            visible = visible && (min_sphere_depth > depth);
        }
    }
    
    if (visible && (!Late || !was_visible_last_frame.v)) {
        uint draw_command_index = atomicAdd(draw_command_count.v, 1);
        
        uint lod_index = 0;
        if (lod_enabled) {
            // lod distance i = base * pow(step, i)
            // i = log2(distance / base) / log2(step)
            float lod_index_f = log2(length(view_center.xyz) / globals.data.lod_base) / log2(globals.data.lod_step);
            lod_index = min(uint(max(lod_index_f + 1, 0)), mesh.v.lod_count - 1);
        }
        
        Mesh_LOD lod = mesh.v.lods[lod_index];
        uint meshlet_group_count = (lod.meshlet_count + TaskWidth-1) / TaskWidth;
        
        Draw_Command_p draw_command = globals.draw_command_buffer[draw_command_index];
        
        draw_command.v.draw_id        = draw_index;
        draw_command.v.meshlet_count  = lod.meshlet_count;
        draw_command.v.meshlet_offset = lod.meshlet_offset;
        
        draw_command.v.command.groupCountX = meshlet_group_count;
        draw_command.v.command.groupCountY = 1;
        draw_command.v.command.groupCountZ = 1;
    }
    
    if (Late) was_visible_last_frame.v = visible;
}