#version 460

#extension GL_EXT_nonuniform_qualifier: require
#extension GL_EXT_shader_explicit_arithmetic_types_int64: require

#include "common.glslh"

layout(local_size_x = 32, local_size_y = 32, local_size_z = 1) in;

layout(binding = 0)       uniform           texture2D Input;
layout(binding = 1)       uniform           sampler   depth_sampler;
layout(binding = 2, r32f) uniform writeonly image2D   Output;

// @volatile
layout(push_constant) uniform Push_Data {
    Depth_Globals globals;
};


void main() {
    uvec2 pixel = gl_GlobalInvocationID.xy;
    
    vec2 uv = (vec2(pixel)+0.5) / globals.size;
    #ifdef HEAP
    vec4 depth4 = textureGather(sampler2D(textures_heap[nonuniformEXT(globals.texture_index)], global_sampler), uv);
    #else
    vec4 depth4 = textureGather(sampler2D(Input, depth_sampler), uv);
    #endif
    float depth = min( min(depth4.x, depth4.y), min(depth4.z, depth4.w) );
    
    imageStore(Output, ivec2(pixel), vec4(depth));
}