#version 460

#include "common.glsl"

layout(local_size_x = 32, local_size_y = 32, local_size_z = 1) in;

layout(push_constant) uniform Push_Data { Depth_Data data; };

layout(descriptor_heap) uniform texture2D Textures[];
layout(descriptor_heap) uniform sampler   Samplers[];
layout(descriptor_heap, r32f) uniform writeonly image2D Images[];

void main() {
    uvec2 pixel = gl_GlobalInvocationID.xy;
    
    vec2 uv = (vec2(pixel)+0.5) / data.size;
    
    // depth_sampler is set up to do min reduction
    float depth = texture(sampler2D(Textures[data.input_index], Samplers[Sampler_Depth]), uv).x;
    
    imageStore(Images[data.output_index], ivec2(pixel), vec4(depth));
}