#version 460

#extension GL_KHR_shader_subgroup_ballot: require

#include "common.h"

#define ComputeWidth 32

layout(local_size_x = ComputeWidth, local_size_y = 1, local_size_z = 1) in;

// @volatile
layout(buffer_reference, buffer_reference_align = 8) buffer Culling_Globals {
    vec4 frustum_planes[6];
};

// @volatile
layout(push_constant) uniform Push_Data {
    Culling_Globals globals;
} push;

// @volatile
layout(binding = 0) readonly buffer Draws {
	Draw draw_buffer[];
};

// @volatile
layout(binding = 1) writeonly buffer Draw_Commands {
    Draw_Command draw_command_buffer[];
};

// @volatile
layout(binding = 2) buffer Draw_Count {
    uint draw_command_count;
};

// @note(viktor): the ballot code assumes that the subgroup size is 32, which needs to be revised for non NVidia archs.

void main() {
    uint group_index  = gl_WorkGroupID.x;
    uint thread_index = gl_LocalInvocationID.x;
    uint draw_index   = group_index * ComputeWidth + thread_index;
    
    Draw draw = draw_buffer[draw_index];
    
    vec3  center = transform(draw.orientation, draw.scale, draw.p, draw.center);
    float radius = draw.radius * draw.scale;
    
    bool visible = true;
    for (int i = 0; i < 6; i++) {
        vec4 plane = push.globals.frustum_planes[i];
        visible = visible && (dot(plane, vec4(center, 1)) > -radius);
    }
    
    uvec4 ballot = subgroupBallot(visible);
    uint index   = subgroupBallotExclusiveBitCount(ballot); // how many threads, before this thread, had accept==true
    uint count   = subgroupBallotBitCount(ballot);          // how many threads, in total, had accept==true
    
    if (count == 0) return;
    
    uint draw_command_group_index = 0;
    if (thread_index == 0) {
        draw_command_group_index = atomicAdd(draw_command_count, count);
    }
    
    uint draw_command_index = subgroupBroadcastFirst(draw_command_group_index) + index;
    
    
    // @note(viktor): when disabling culling and drawing every mesh, there was a flickering every n-th frame.
    // The meshes were not drawn for about one frame and then it was stable again for a while. This repeated
    // indefinitly.
    if (visible) {
        draw_command_buffer[draw_command_index].draw_id = draw_index;
        
        draw_command_buffer[draw_command_index].groupCountX = (draw.meshlet_count + TaskWidth-1) / TaskWidth;
        draw_command_buffer[draw_command_index].groupCountY = 1;
        draw_command_buffer[draw_command_index].groupCountZ = 1;
    }
}