#version 460

#include "common.h"

#define ComputeWidth 32

layout(local_size_x = ComputeWidth, local_size_y = 1, local_size_z = 1) in;

// @volatile
layout(buffer_reference, buffer_reference_align = 8) buffer Culling_Globals {
    vec4 frustum_planes[6];
};

// @volatile
layout(push_constant) uniform Push_Data {
    Culling_Globals globals;
} push;

// @volatile
layout(binding = 0) readonly buffer Draws {
	Draw draw_buffer[];
};

// @volatile
layout(binding = 1) writeonly buffer Draw_Commands {
    Draw_Command draw_command_buffer[];
};

void main() {
    uint group_index  = gl_WorkGroupID.x;
    uint thread_index = gl_LocalInvocationID.x;
    uint draw_index   = group_index * ComputeWidth + thread_index;
    
    Draw draw = draw_buffer[draw_index];
    
    vec3  center = transform(draw.orientation, draw.scale, draw.p, draw.center);
    float radius = draw.radius * draw.scale;
    
    bool visible = true;
    for (int i = 0; i < 6; i++) {
        vec4 plane = push.globals.frustum_planes[i];
        visible = visible && (dot(plane, vec4(center, 1)) > -radius);
    }
    // int i = 5;
    // vec4 plane = push.globals.frustum_planes[i];
    // visible = visible && (dot(plane, vec4(center, 1)) > -radius);
    
    draw_command_buffer[draw_index].groupCountX = visible ? (draw.meshlet_count + TaskWidth-1) / TaskWidth : 0;
    draw_command_buffer[draw_index].groupCountY = 1;
    draw_command_buffer[draw_index].groupCountZ = 1;
}