#version 460

#extension GL_EXT_buffer_reference: require
#extension GL_EXT_buffer_reference2: require
#extension GL_EXT_shader_explicit_arithmetic_types_int64: require
#extension GL_KHR_shader_subgroup_ballot: require

#include "common.h"

#define ComputeWidth 32

layout(local_size_x = ComputeWidth, local_size_y = 1, local_size_z = 1) in;

layout(buffer_reference, buffer_reference_align = 16) buffer Draw_p         { Draw         v; };
layout(buffer_reference, buffer_reference_align = 16) buffer Draw_Command_p { Draw_Command v; };
layout(buffer_reference, buffer_reference_align = 4)  buffer uint_p         { uint         v; };

// @volatile
layout(buffer_reference, buffer_reference_align = 8) buffer Cull_Globals {
    vec4 frustum_planes[6];
	Draw_p         draw_array;
	Draw_Command_p draw_command_array;
	uint_p         draw_command_count;
};

// @volatile
layout(push_constant) uniform Push_Data {
    Cull_Globals globals;
};

// @note(viktor): the ballot code assumes that the subgroup size is 32, which needs to be revised for non NVidia archs.

void main() {
    uint group_index  = gl_WorkGroupID.x;
    uint thread_index = gl_LocalInvocationID.x;
    uint draw_index   = group_index * ComputeWidth + thread_index;
    
    
    Draw_p draw               = globals.draw_array[draw_index];
    uint_p draw_command_count = globals.draw_command_count;
    
    vec3  center = transform(draw.v.orientation, draw.v.scale, draw.v.p, draw.v.center);
    float radius = draw.v.radius * draw.v.scale;
    
    bool visible = true;
    for (int i = 0; i < 6; i++) {
        vec4 plane = globals.frustum_planes[i];
        visible = visible && (dot(plane, vec4(center, 1)) > -radius);
    }
    
    uvec4 ballot = subgroupBallot(visible);
    uint index   = subgroupBallotExclusiveBitCount(ballot); // how many threads, before this thread, had accept==true
    uint count   = subgroupBallotBitCount(ballot);          // how many threads, in total, had accept==true
    
    if (count == 0) return;
    
    uint draw_command_group_index = 0;
    if (thread_index == 0) {
        draw_command_group_index = atomicAdd(draw_command_count.v, count);
    }
    
    uint draw_command_index = subgroupBroadcastFirst(draw_command_group_index) + index;
    
    
    // @note(viktor): when disabling culling and drawing every mesh, there was a flickering every n-th frame.
    // The meshes were not drawn for about one frame and then it was stable again for a while. This repeated
    // indefinitly.
    if (visible) {
        Draw_Command_p draw_command = globals.draw_command_array[draw_command_index];
        draw_command.v.draw_id = draw_index;
        
        draw_command.v.groupCountX = (draw.v.meshlet_count + TaskWidth-1) / TaskWidth;
        draw_command.v.groupCountY = 1;
        draw_command.v.groupCountZ = 1;
    }
}